version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: stats_image
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=explore_with_me_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats_db
      - DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats_db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore_with_me_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: main_service
    image: main_service_image
    container_name: main_service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - DB_NAME=explore_with_me_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=main_service_db
      - DB_PORT=5433

  main-db:
    image: postgres:13.7-alpine
    container_name: main_service_db
    ports:
      - "5433:5433"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore_with_me_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
