version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    image: stats_image
    container_name: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STAT_DB_NAME=explore_with_me_stats
      - STAT_POSTGRES_USER=root
      - STAT_POSTGRES_PASSWORD=root
      - STAT_DB_HOST=stats_db
      - STAT_DB_PORT=5432

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats_db
    ports:
      - "5432:5432"
    volumes:
      - stats_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore_with_me_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main_service
    image: ewm_image
    container_name: ewm
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EWM_DB_NAME=explore_with_me
      - EWM_POSTGRES_USER=root
      - EWM_POSTGRES_PASSWORD=root
      - EWM_DB_HOST=ewm_db
      - EWM_DB_PORT=5433

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm_db
    ports:
      - "5433:5433"
    volumes:
      - ewm_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    command: -p 5433
volumes:
  ewm_data:
  stats_data:
